spring.application.name=ea_Springboot_JDBC
spring.mvc.view.prefix=/views/
spring.mvc.view.suffix=.jsp

#-------Database Details-------
spring.datasource.url=jdbc:mysql://localhost:3306/springboot_jdbc_db
spring.datasource.username=root
spring.datasource.password=root