spring.application.name=ia_Springboot_Data_JPA-1


spring.datasource.url=jdbc:mysql://localhost:3306/crud_restapi
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true