spring.application.name=fa_Springboot_Registration_App
spring.mvc.view.prefix=/views/
spring.mvc.view.suffix=.jsp

#-------Database Details-------
spring.datasource.url=jdbc:mysql://localhost:3306/springboot_jdbc_db
spring.datasource.username=root
spring.datasource.password=root
